# Generated by Django 4.2.6 on 2024-01-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('age', models.CharField(max_length=100, verbose_name='last name')),
                ('id_no', models.CharField(max_length=20, null=True, verbose_name='id number')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='mobile number')),
                ('subject_tutored', models.CharField(max_length=30, verbose_name='subject tutored')),
                ('street_address', models.CharField(max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(max_length=500, verbose_name='biography')),
                ('highest_qualification', models.CharField(max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanTutorOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_grade', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LessonMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_mode', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LessonStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_start', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('contactnumber', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_tutored', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_syllabus', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UnderGrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undergrad_finished', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=300)),
                ('parent_name', models.CharField(max_length=50)),
                ('learner_name', models.CharField(max_length=50)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GetTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('street_address', models.CharField(max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('additional_details', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pay_rate', models.CharField(max_length=7)),
                ('job_number', models.CharField(max_length=5, null=True, unique=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.grade')),
                ('jobstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.jobstatus')),
                ('lesson_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.lessonmode')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.province')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.relationship')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.lessonstart')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.subject')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('body', models.TextField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='can_tutor_online',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.cantutoronline'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.gender'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.province'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='sa_citizen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.citizen'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='undergrad_finished',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greatmindzapp.undergrad'),
        ),
    ]
